### ISSUE TITLE
errors aren't Error objects

### ISSUE THREAD

**Issue by cappslock** [GetStream/stream-js#113]
For most (all?) operations that potentially pass errors to callbacks or reject promises, the error objects are plain objects instead of actual Error objects. This is inconsistent with the node ecosystem and creates some issues when trying to integrate with services like Sentry. It would be nice if these were actual Error objects, or a subclass of Error specific to GetStream.

**Comment by dwightgunning** [comment]
Thanks for pointing this out!

All the API operation functions involve the `wrapPromise()` function which deconstructs the response (or error) of the HTTP request.

The fix I have in mind is to change this function to reject / callback with an error that is new custom Error class. The custom error will still expose the 'error' and 'response' properties in order to minimise the chance of breaking existing implementations.

Here's what I've got so far, and feedback appreciated.

https://github.com/dwightgunning/stream-js/commit/3ffbb4d02456c95cad4a08bfe3e253dd7a3ebe66

If that looks like a reasonable approach we can look to get this out shortly in a new release.

**Comment by cappslock** [comment]
Hey @dwightgunning, thanks for the reply! I left a comment in the PR of one small issue. This feels like the right fix to me - although I'm biased because it's eerily similar to my workaround.

**Comment by dwightgunning** [comment]
Thanks for the review and picking that up! Since this will be a potential break for some people, we'll do a major release. That may make it a good time to include some other changes we've had in the wings for a while. I will come back to you shortly with guidance on when we're likely to get this packaged and released.
