### ISSUE TITLE
Parsing error: Unexpected token, expected } (Fatal)

### ISSUE THREAD

**Issue by Gabsys** [GetStream/stream-js#159]
In `  chris.addActivity({
        actor: 'chris',
        verb: 'add',
        object: 'picture:10',
        foreign_id: 'picture:10',
        message: 'Beautiful bird!'    })`

there are Parsing errors at all the props (actor, verb, object, foreign_id, message), anyone have any clue?

**Comment by dwightgunning** [comment]
This is a parsing error with your JavaScript program. Per the error description you've pasted into the Issue title, the parser is expecting a '}' token but encountered some other token.

The 'addActivity()' line of code looks syntactically correct so most likely the error is elsewhere in your program. Take a look at the full error and stack trace as there maybe a reference to the line number where the error is identified. Most likely the error is due to an un-balanced or incorrectly placed parenthesis or brace token.

I'll close this off for now but we can re-open if some new information points to an issue within the stream-js codebase.
