### ISSUE TITLE
how to get enriched activity?

### ISSUE THREAD

**Issue by mikestaub** [GetStream/stream-js#207]
Is there a way to subscribe to a feed and receive enriched activities?

This is how I am subscribing to changes:

```
    var stream = require("getstream");
    var client = stream.connectCloud("YOUR_API_KEY", "APP_ID", {
      location: "us-east",
    });
    var feed = client.feed("notification", "1", "USER_SESSION_TOKEN");
    var subscription = feed.subscribe(async function(data) {
      console.log(data);
	  var activityId = data.new[0].id;
      var res1 = await feed.getActivityDetail(activityId);
	  var res2 = await feed.get({ limit: 20, offset: 0 });
    });
```

When I log the data, it is not enriched, as the actor is a string ( 'SO:user:a4a918a1d5fb4602ba532b60aa4c00e9' ). The activities in res1 and res2 _are_ enriched however.

When I try to get the details of the activity using its id, I simply get back the full activities group, not including the id I specified. Both res1 and res2 are identical, which seems like a bug.

**Comment by JelteF** [comment]
@mikestaub at the moment activities received through subscriptions are indeed not enriched. This is in the planning though. For the moment your workaround of getting the feed is the recommended way to do this.

**Comment by JelteF** [comment]
Ah, I missed that final comment on the getActivityDetail functionality. Is the activity the only one in the feed, because then the responses should indeed be identical. Otherwise it indeed sounds like a bug.

Regarding pulling the entire feed on every update. Usually customers have a notification at the top that says there's new posts in the feed and once the customer clicks that it refreshes the feed. This has as an advantage that the page doesn't change unexpectedly for the user. This might not be fitting for your use case though. In any case I'll post again here when we shipped enrichment of realtime updates.

**Comment by tbarbugli** [comment]
@mikestaub activities are now enriched when pushed as realtime updates
