### ISSUE TITLE
Reaction counts are not included in parent activity

### ISSUE THREAD

**Issue by Crysknight** [GetStream/stream-js#409]
So I use `reactions` option when requesting activities as specified here https://getstream.io/docs/reactions_read_feeds/?language=js
When my feed was flat, that was working perfectly: I was receiving `reaction_counts` in activities for displaying them fast. Then I had to switch my feed to the aggregated type and with this `reaction_counts` were no more appearing in activities (now they were appearing in subactivities).
But I post reactions bound to parent activities ids. And so now I have to specify the last subactivity id which is not so cleanly. Is there any way to have `reaction_counts` on a parent activity? Because the reactions are binding to the parent activity perfectly, and I can retrieve reactions by the parent activity id. It's just the `reaction_counts` that are not working with the aggregated activities.
![image](https://user-images.githubusercontent.com/25486499/103821835-0c759300-5080-11eb-9eb3-937261c98269.png)

gz#8456

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8456'>Zendesk ticket #8456</a>:<br><br>Hi there,

We'll take a look into this as soon as we can.

**Comment by ferhatelmas** [comment]
@Crysknight reactions are counted on activities. What you show above is a group in aggregated feed, it's just a view over activities so it's dynamic according to aggregation function. While adding a reaction, you need to specify id (UUID) of a specific activity so that a reaction is added to an activity. This works as intended.

You can sum up reactions counts of activities in a group if your UI would like to show them a metric.
