### ISSUE TITLE
Crypto dependency missing

### ISSUE THREAD

**Issue by shprink** [GetStream/stream-js#76]
You require crypto in your code but the lib is not in your dependencies. When requiring:

```
import stream from 'getstream';
````

I get this message: "unknown module crypto".

As a work around we can import the dist file:

```
import stream from 'getstream/dist/js/getstream';
```

**Comment by matthisk** [comment]
Crypto is part of the node standard library, so if you are using this client for a node application it should not be necessary to include crypto in the `package.json` dependencies. If you use this library in the browser you shouldn't need crypto because you can only use presigned feed tokens to perform updates or retrieve activities (sharing your getstream secret key to all your clients is a bad idea). If you use a tool like browserify/webpack it should pick up on the `package.json` browser field and not include crypto. Can you please elaborate in what environment you are using this client library and if applicable which build tools you are using.

**Comment by shprink** [comment]
I am using ReactNative

**Comment by matthisk** [comment]
Ok I investigated a bit and think this issue arises because of how we detect whether the package is used in a node or browser environment. To detect the environment we use `window` global variable, but if I am correct there is no `window` global variable in react-native, or is there? I am having some issues running react-native locally (haven't used it before myself) could you help me out pinpointing the origin of this bug, since you are the first user using this library on react-native. Let me know, you can reach me on Skype if you want to chat: tthisk

**Comment by shprink** [comment]
Forgot to mention this happens on Android device

**Comment by matthisk** [comment]
Running with webpack as a bundler instead of react-native packager seems to fix this issue, because webpack adheres to the "browser" field inside `package.json` where the react-native packager ignores this field.
